openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for user authentication and authorization

servers:
  - url: http://localhost:3030
    description: Local server

tags:
  - name: Authentication
    description: User authentication and authorization operations

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: |
        Register a new user account. Returns user data and authentication token for immediate login.
        
        **Rate Limit:** 5 requests per hour per IP
        
        **Validation Rules:**
        - Email: Must be valid email format
        - Password: Minimum 8 characters, must contain uppercase, lowercase, and number
        - Username: 3-30 characters, alphanumeric and underscores only
        - Full Name: Minimum 2 characters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - username
                - fullName
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address (will be converted to lowercase)
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: User's password (min 8 chars, must contain uppercase, lowercase, and number)
                  example: "SecurePass123"
                username:
                  type: string
                  minLength: 3
                  maxLength: 30
                  pattern: "^[a-zA-Z0-9_]+$"
                  description: Unique username (will be converted to lowercase)
                  example: "john_doe"
                fullName:
                  type: string
                  minLength: 2
                  description: User's full name
                  example: "John Doe"
      responses:
        '201':
          description: User registered successfully with authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User registered successfully"
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/UserResponse'
                      token:
                        type: string
                        description: JWT authentication token (valid for 7 days)
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '409':
          description: Conflict - email or username already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Rate limit exceeded (5 requests per hour)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login user
      description: |
        Authenticate user and receive authentication token. Updates user's lastSeen timestamp.
        
        **Rate Limit:** 10 requests per 15 minutes per IP
        
        **Notes:**
        - Blocked users cannot login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  description: User's password
                  example: "SecurePass123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Login successful"
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/UserResponse'
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: User is blocked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/password-reset/request:
    post:
      tags:
        - Authentication
      summary: Request password reset
      description: |
        Request a password reset email to be sent to the user's registered email address.
        
        **Rate Limit:** 3 requests per hour per IP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: User's registered email address
                  example: "user@example.com"
      responses:
        '200':
          description: Password reset email sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "If an account with that email exists, a password reset email has been sent"
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/password-reset/confirm:
    post:
      tags:
        - Authentication
      summary: Confirm password reset
      description: |
        Reset user's password using the token received via email.
        
        **Rate Limit:** 3 requests per hour per IP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  description: Password reset token from email
                  example: "abc123def456"
                newPassword:
                  type: string
                  format: password
                  minLength: 8
                  description: New password (same validation rules as registration)
                  example: "NewSecurePass123"
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Password has been reset successfully"
        '400':
          description: Invalid or expired token, or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    UserResponse:
      type: object
      properties:
        _id:
          type: string
          example: "6510d1a2b3c4d5e6f7890123"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        username:
          type: string
          example: "johndoe"
        fullName:
          type: string
          example: "John Doe"
        role:
          type: string
          enum: [user, admin]
          example: "user"
        isBlocked:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ValidationError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: "VALIDATION_ERROR"
            message:
              type: string
              example: "Validation failed"
            details:
              type: object
              properties:
                fields:
                  type: object
                  additionalProperties:
                    type: string

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: "ERROR_CODE"
            message:
              type: string
              example: "Error message"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from login or register endpoints
