openapi: 3.0.0
info:
  title: Comment API
  version: 1.0.0
  description: API for managing comments on posts

servers:
  - url: http://localhost:3030
    description: Development server

tags:
  - name: Comments
    description: Comment management operations

paths:
  /posts/{postId}/comments:
    post:
      tags:
        - Comments
      summary: Create a comment or reply
      description: Creates a new comment on a post or a reply to an existing comment. Replies are limited to one level deep.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            format: objectId
          description: ID of the post to comment on
          example: "507f1f77bcf86cd799439011"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  minLength: 1
                  maxLength: 2000
                  description: The content of the comment
                  example: "Great post! Thanks for sharing."
                parentCommentId:
                  type: string
                  format: objectId
                  description: ID of the parent comment if this is a reply
                  example: "507f1f77bcf86cd799439012"
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Comment created successfully"
                  data:
                    type: object
                    properties:
                      comment:
                        $ref: '#/components/schemas/Comment'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Post or parent comment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

    get:
      tags:
        - Comments
      summary: Get comments for a post
      description: Retrieves comments for a specific post with pagination. Can filter by parentCommentId to get replies.
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
            format: objectId
          description: ID of the post
          example: "507f1f77bcf86cd799439011"
        - in: query
          name: parentCommentId
          schema:
            type: string
            format: objectId
          description: Filter by parent comment ID to get replies
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of comments per page
      responses:
        '200':
          description: Comments retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      comments:
                        type: array
                        items:
                          $ref: '#/components/schemas/Comment'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /comments/{id}:
    put:
      tags:
        - Comments
      summary: Update a comment
      description: Updates the content of a comment. Only the comment author or an admin can update it.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: objectId
          description: ID of the comment to update
          example: "507f1f77bcf86cd799439011"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  minLength: 1
                  maxLength: 2000
                  description: Updated content of the comment
                  example: "Updated comment content"
      responses:
        '200':
          description: Comment updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Comment updated successfully"
                  data:
                    type: object
                    properties:
                      comment:
                        $ref: '#/components/schemas/Comment'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Not authorized to update this comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Comment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - Comments
      summary: Delete a comment
      description: Deletes a comment. Only the comment author or an admin can delete it.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: objectId
          description: ID of the comment to delete
          example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Comment deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Comment deleted successfully"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Not authorized to delete this comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Comment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /comments/{id}/like:
    post:
      tags:
        - Comments
      summary: Like a comment
      description: Adds a like to a comment by the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: objectId
          description: ID of the comment to like
          example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Comment liked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Comment liked successfully"
                  data:
                    type: object
                    properties:
                      likesCount:
                        type: integer
                        example: 15
        '400':
          description: Already liked this comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Comment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - Comments
      summary: Unlike a comment
      description: Removes a like from a comment by the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: objectId
          description: ID of the comment to unlike
          example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Comment unliked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Comment unliked successfully"
                  data:
                    type: object
                    properties:
                      likesCount:
                        type: integer
                        example: 14
        '400':
          description: Not liked this comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Comment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    Comment:
      type: object
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
        content:
          type: string
          example: "Great post!"
        author:
          type: object
          properties:
            _id:
              type: string
            username:
              type: string
            fullName:
              type: string
            profilePicture:
              type: string
        post:
          type: string
          example: "507f1f77bcf86cd799439012"
        parentComment:
          type: string
          nullable: true
          example: null
        likesCount:
          type: integer
          example: 5
        repliesCount:
          type: integer
          example: 2
        isLiked:
          type: boolean
          description: Whether the authenticated user has liked this comment
          example: false
        editedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 20
        total:
          type: integer
          example: 100
        pages:
          type: integer
          example: 5

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Error message"

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Authentication required"

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Internal server error"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
