openapi: 3.0.0
info:
  title: Connection API
  version: 1.0.0
  description: API for managing user connections (follow/unfollow)

servers:
  - url: http://localhost:3030
    description: Development server

tags:
  - name: Connections
    description: User connection operations (follow, unfollow)

paths:
  /users/{userId}/follow:
    post:
      tags:
        - Connections
      summary: Follow a user
      description: Creates a follow connection to another user. Increments follower/following counts.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          description: MongoDB ObjectId of the user to follow
          example: "507f1f77bcf86cd799439012"
      responses:
        '200':
          description: Successfully followed user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Successfully followed user"
                  data:
                    type: object
                    properties:
                      followedUserId:
                        type: string
                        example: "507f1f77bcf86cd799439012"
                      followedAt:
                        type: string
                        format: date-time
        '400':
          description: Bad request (self-follow, already following, or blocked)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                self_follow:
                  summary: Cannot follow yourself
                  value:
                    success: false
                    message: "Cannot follow yourself"
                already_following:
                  summary: Already following
                  value:
                    success: false
                    message: "Already following this user"
                blocked:
                  summary: Block exists
                  value:
                    success: false
                    message: "Cannot follow this user due to a block"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - Connections
      summary: Unfollow a user
      description: Removes the follow connection to another user. Decrements follower/following counts.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          description: MongoDB ObjectId of the user to unfollow
          example: "507f1f77bcf86cd799439012"
      responses:
        '200':
          description: Successfully unfollowed user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Successfully unfollowed user"
                  data:
                    type: object
                    properties:
                      unfollowedUserId:
                        type: string
                        example: "507f1f77bcf86cd799439012"
        '400':
          description: Not following this user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /users/{userId}/followers:
    get:
      tags:
        - Connections
      summary: Get user's followers
      description: Returns a paginated list of users who follow the specified user. Optionally includes isFollowing status when authenticated.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          description: MongoDB ObjectId of the user
          example: "507f1f77bcf86cd799439011"
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Items per page
      responses:
        '200':
          description: List of followers retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      followers:
                        type: array
                        items:
                          $ref: '#/components/schemas/UserProfile'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
        '400':
          description: Invalid user ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /users/{userId}/following:
    get:
      tags:
        - Connections
      summary: Get users that this user follows
      description: Returns a paginated list of users that the specified user follows. Optionally includes isFollowing status when authenticated.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          description: MongoDB ObjectId of the user
          example: "507f1f77bcf86cd799439011"
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Items per page
      responses:
        '200':
          description: List of following retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      following:
                        type: array
                        items:
                          $ref: '#/components/schemas/UserProfile'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
        '400':
          description: Invalid user ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    UserProfile:
      type: object
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
        username:
          type: string
          example: "johndoe"
        fullName:
          type: string
          example: "John Doe"
        profilePicture:
          type: string
          format: uri
        bio:
          type: string
        isFollowing:
          type: boolean
          description: Whether the authenticated user is following this user

    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 20
        total:
          type: integer
          example: 100
        pages:
          type: integer
          example: 5

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Error message"

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Authentication required"

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Internal server error"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
