openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for managing users

servers:
  - url: http://localhost:3030
    description: Development server

tags:
  - name: Users
    description: User management operations

paths:
  /users/{username}:
    get:
      tags:
        - Users
      summary: Get user profile by username
      description: Returns the public profile of a user. When authenticated, also includes relationship information (isFollowing, followsYou).
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 30
          description: Username of the user to retrieve
          example: "johndoe"
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/UserProfileResponse'
        '403':
          description: User is blocked or has blocked you
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "You cannot view this profile"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "User not found"
        '500':
          $ref: '#/components/responses/ServerError'

  /users/profile:
    put:
      tags:
        - Users
      summary: Update own profile
      description: Allows authenticated user to update their profile information. Only provided fields will be updated.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  minLength: 2
                  maxLength: 50
                  example: "John Smith"
                bio:
                  type: string
                  maxLength: 300
                  example: "Full-stack developer passionate about open source"
                specialization:
                  type: string
                  maxLength: 100
                  example: "React & Node.js Developer"
                location:
                  type: string
                  maxLength: 100
                  example: "San Francisco, CA"
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Profile updated successfully"
                  data:
                    $ref: '#/components/schemas/UserProfileResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "Validation failed"
                errors:
                  fullName: "Full name must be between 2 and 50 characters"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /users/profile/picture:
    post:
      tags:
        - Users
      summary: Upload profile picture
      description: Upload or update the authenticated user's profile picture. Image will be processed (resized to 500x500, compressed, converted to WebP) and uploaded to cloud storage.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: Profile picture image file (JPEG, PNG, or WebP)
      responses:
        '200':
          description: Profile picture uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile picture updated successfully"
                  profilePicture:
                    type: string
                    format: uri
                    example: "https://res.cloudinary.com/example/image/upload/profile-pictures/user_123_1234567890.webp"
        '400':
          description: Bad request (no file, invalid type, file too large, or corrupted image)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                no_file:
                  summary: No file uploaded
                  value:
                    error: "No file uploaded"
                invalid_type:
                  summary: Invalid file type
                  value:
                    error: "Invalid file type. Only JPEG, PNG, and WebP are allowed."
                corrupted:
                  summary: Corrupted image
                  value:
                    error: "Corrupted or invalid image file"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error (processing or upload failed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                processing_error:
                  summary: Image processing failed
                  value:
                    error: "Failed to process image"
                upload_error:
                  summary: Cloud upload failed
                  value:
                    error: "Failed to upload image"

  /users/profile/cover:
    post:
      tags:
        - Users
      summary: Upload cover image
      description: Upload or update the authenticated user's cover image. Image will be processed (resized to 1500x500, compressed, converted to WebP) and uploaded to cloud storage.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: Cover image file (JPEG, PNG, or WebP)
      responses:
        '200':
          description: Cover image uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cover image updated successfully"
                  coverImage:
                    type: string
                    format: uri
                    example: "https://res.cloudinary.com/example/image/upload/cover-images/user_123_1234567890.webp"
        '400':
          description: Bad request (no file, invalid type, file too large, or corrupted image)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{userId}/block:
    post:
      tags:
        - Users
      summary: Block a user
      description: Block a user. Blocked users cannot view your profile, follow you, or message you.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          description: MongoDB ObjectId of the user to block
          example: "507f1f77bcf86cd799439012"
      responses:
        '200':
          description: User blocked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User blocked successfully"
        '400':
          description: Cannot block yourself or already blocked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - Users
      summary: Unblock a user
      description: Unblock a previously blocked user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          description: MongoDB ObjectId of the user to unblock
          example: "507f1f77bcf86cd799439012"
      responses:
        '200':
          description: User unblocked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User unblocked successfully"
        '400':
          description: User not blocked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

  /users/{userId}/posts:
    get:
      tags:
        - Users
      summary: Get user's posts
      description: Retrieves posts created by a specific user with pagination
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          description: MongoDB ObjectId of the user
          example: "507f1f77bcf86cd799439011"
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          description: Number of posts per page
      responses:
        '200':
          description: User's posts retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      posts:
                        type: array
                        items:
                          $ref: '#/components/schemas/Post'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
        '400':
          description: Invalid user ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    UserProfileResponse:
      type: object
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
        username:
          type: string
          example: "johndoe"
        fullName:
          type: string
          example: "John Doe"
        bio:
          type: string
          example: "Full-stack developer"
        specialization:
          type: string
          example: "React & Node.js"
        location:
          type: string
          example: "San Francisco, CA"
        profilePicture:
          type: string
          format: uri
        coverImage:
          type: string
          format: uri
        followersCount:
          type: integer
          example: 150
        followingCount:
          type: integer
          example: 75
        postsCount:
          type: integer
          example: 42
        isFollowing:
          type: boolean
          description: Whether the authenticated user is following this user
          example: false
        followsYou:
          type: boolean
          description: Whether this user follows the authenticated user
          example: false
        isBlocked:
          type: boolean
          description: Whether the authenticated user has blocked this user
          example: false
        createdAt:
          type: string
          format: date-time

    Post:
      type: object
      properties:
        _id:
          type: string
        content:
          type: string
        author:
          type: object
          properties:
            _id:
              type: string
            username:
              type: string
            fullName:
              type: string
            profilePicture:
              type: string
        images:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        likesCount:
          type: integer
        commentsCount:
          type: integer
        repostsCount:
          type: integer
        isLiked:
          type: boolean
        isSaved:
          type: boolean
        createdAt:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 10
        total:
          type: integer
          example: 100
        pages:
          type: integer
          example: 10

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Error message"

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Authentication required"

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Internal server error"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
