openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for managing users

servers:
  - url: http://localhost:3030
    description: Development server

paths:
  /users/{username}:
    get:
      tags:
        - Users
      summary: Get user profile by username
      description: Returns the public profile of a user. When authenticated, also includes relationship information (isFollowing, followsYou).
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 30
          description: Username of the user to retrieve
          example: "johndoe"
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/UserProfileResponse'
        '403':
          description: User is blocked or has blocked you
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                blocked:
                  summary: User blocked
                  value:
                    success: false
                    message: "Access to this profile is restricted"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                not_found:
                  summary: User does not exist
                  value:
                    success: false
                    message: "User not found"
        '500':
          $ref: '#/components/responses/ServerError'

  /users/profile:
    put:
      tags:
        - Users
      summary: Update own profile
      description: Allows authenticated user to update their profile information. Only provided fields will be updated.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  minLength: 2
                  maxLength: 50
                  example: "John Smith"
                bio:
                  type: string
                  maxLength: 300
                  example: "Full-stack developer passionate about open source"
                specialization:
                  type: string
                  maxLength: 100
                  example: "React & Node.js Developer"
                location:
                  type: string
                  maxLength: 100
                  example: "San Francisco, CA"
                profilePicture:
                  type: string
                  format: uri
                  example: "https://example.com/profile.jpg"
                coverImage:
                  type: string
                  format: uri
                  example: "https://example.com/cover.jpg"
            examples:
              update_bio:
                summary: Update bio and specialization
                value:
                  bio: "Senior software engineer with 5 years of experience"
                  specialization: "Backend Architecture"
              update_full_profile:
                summary: Update multiple fields
                value:
                  fullName: "John Smith"
                  bio: "Tech enthusiast and coffee lover"
                  specialization: "DevOps Engineer"
                  location: "New York, NY"
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Profile updated successfully"
                  data:
                    $ref: '#/components/schemas/UserProfileResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                validation_error:
                  summary: Invalid field values
                  value:
                    success: false
                    message: "Validation failed"
                    errors:
                      fullName: "Full name must be between 2 and 50 characters"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'

  /users/profile/picture:
    post:
      tags:
        - Users
      summary: Upload profile picture
      description: Upload or update the authenticated user's profile picture. Image will be processed (resized to 500x500, compressed, converted to WebP) and uploaded to cloud storage.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: Profile picture image file (JPEG, PNG, or WebP)
      responses:
        '200':
          description: Profile picture uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile picture updated successfully"
                  profilePicture:
                    type: string
                    format: uri
                    example: "https://res.cloudinary.com/example/image/upload/profile-pictures/user_123_1234567890.webp"
        '400':
          description: Bad request (no file, invalid type, file too large, or corrupted image)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                no_file:
                  summary: No file uploaded
                  value:
                    error: "No file uploaded"
                invalid_type:
                  summary: Invalid file type
                  value:
                    error: "Invalid file type. Only JPEG, PNG, and WebP are allowed."
                file_too_large:
                  summary: File size exceeds limit
                  value:
                    success: false
                    message: "File size exceeds the allowed limit."
                corrupted:
                  summary: Corrupted image
                  value:
                    error: "Corrupted or invalid image file"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "User not found"
        '500':
          description: Server error (processing or upload failed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                processing_error:
                  summary: Image processing failed
                  value:
                    error: "Failed to process image"
                upload_error:
                  summary: Cloud upload failed
                  value:
                    error: "Failed to upload image"

  /users/profile/cover:
    post:
      tags:
        - Users
      summary: Upload cover image
      description: Upload or update the authenticated user's cover image. Image will be processed (resized to 1500x500, compressed, converted to WebP) and uploaded to cloud storage.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: Cover image file (JPEG, PNG, or WebP)
      responses:
        '200':
          description: Cover image uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cover image updated successfully"
                  coverImage:
                    type: string
                    format: uri
                    example: "https://res.cloudinary.com/example/image/upload/cover-images/user_123_1234567890.webp"
        '400':
          description: Bad request (no file, invalid type, file too large, or corrupted image)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                no_file:
                  summary: No file uploaded
                  value:
                    error: "No file uploaded"
                invalid_type:
                  summary: Invalid file type
                  value:
                    error: "Invalid file type. Only JPEG, PNG, and WebP are allowed."
                file_too_large:
                  summary: File size exceeds limit
                  value:
                    success: false
                    message: "File size exceeds the allowed limit."
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "User not found"
        '500':
          description: Server error (processing or upload failed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                processing_error:
                  summary: Image processing failed
                  value:
                    error: "Failed to process image"
                upload_error:
                  summary: Cloud upload failed
                  value:
                    error: "Failed to upload image"

components:
  schemas:
    UserProfileResponse:
      type: object
      description: User profile response for Epic 2 endpoints
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
        username:
          type: string
          example: "johndoe"
        fullName:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        bio:
          type: string
          nullable: true
          example: "Software engineer passionate about clean code"
        specialization:
          type: string
          nullable: true
          example: "Frontend Development"
        location:
          type: string
          nullable: true
          example: "San Francisco, CA"
        profilePicture:
          type: string
          nullable: true
          example: "https://example.com/profile.jpg"
        coverImage:
          type: string
          nullable: true
          example: "https://example.com/cover.jpg"
        followersCount:
          type: integer
          example: 150
        followingCount:
          type: integer
          example: 200
        postsCount:
          type: integer
          example: 42
        createdAt:
          type: string
          format: date-time
          example: "2025-01-15T10:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-12-13T10:00:00.000Z"
        isFollowing:
          type: boolean
          description: Present only when request is authenticated. Indicates if the current user follows this profile.
          example: true
        followsYou:
          type: boolean
          description: Present only when request is authenticated. Indicates if this profile follows the current user.
          example: false

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Error message"

  responses:
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "NO_TOKEN"
                  message:
                    type: string
                    example: "Authentication required"

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: "Internal server error"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /auth/register or /auth/login

tags:
  - name: Users
    description: |
      User management operations including profile management and image uploads.
      
      ## File Upload Requirements
      
      ### Profile Picture Upload
      - **Endpoint**: POST /users/profile/picture
      - **Field name**: `image`
      - **Max size**: 5 MB
      - **Allowed types**: JPEG, PNG, WebP
      - **Processing**: Resized to 500x500px, compressed, converted to WebP (quality 85)
      - **Storage**: Cloudinary folder `profile-pictures`
      - **Behavior**: Replaces existing profile picture (old image is automatically deleted)
      
      ### Cover Image Upload
      - **Endpoint**: POST /users/profile/cover
      - **Field name**: `image`
      - **Max size**: 10 MB
      - **Allowed types**: JPEG, PNG, WebP
      - **Processing**: Resized to 1500x500px, compressed, converted to WebP (quality 85)
      - **Storage**: Cloudinary folder `cover-images`
      - **Behavior**: Replaces existing cover image (old image is automatically deleted)
      
      ### Processing Details
      All uploaded images are:
      - Validated for file type using magic number detection (not just extension)
      - Validated for file integrity using Sharp
      - Processed locally with Sharp (resize, compress, WebP conversion)
      - Stripped of metadata for privacy
      - Uploaded to Cloudinary for CDN delivery
      
      ### Error Handling
      - File size limits enforced by Multer middleware (returns 400)
      - Invalid file types rejected (returns 400)
      - Corrupted images rejected (returns 400)
      - Processing failures return 500
      - Upload failures return 500

